In [48]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [49]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [51]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [52]:
df=pd.read_csv("Iris.csv")

In [53]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [55]:
df_x=df.drop("Species", axis=1)

In [56]:
df_y=df.Species

In [58]:
x_train,x_test, y_train, y_test= train_test_split(df_x, df_y,test_size=0.33 ,random_state=42)

In [59]:
reg=GaussianNB()

In [60]:
reg

GaussianNB()

In [61]:
reg.fit(x_train, y_train)

GaussianNB()

In [62]:
y_pred=reg.predict(x_test)

In [63]:
y_pred[0]

np.str_('Iris-versicolor')

In [64]:
cm=confusion_matrix(y_test, y_pred)

In [68]:
print("confusion Matrix")
print(cm)
print("Accuarcy :", accuracy_score(y_test, y_pred))
print("error :", 1-accuracy_score(y_test, y_pred))
print("Precision :", precision_score(y_test, y_pred, average='macro'))
print("Recall :", recall_score(y_test, y_pred, average='macro'))

confusion Matrix
[[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]
Accuarcy : 1.0
error : 0.0
Precision : 1.0
Recall : 1.0
